version: '3.8'

services:
  menu_app:
    container_name: menuapp
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    entrypoint:
      sh -c "
      cd alembic && mkdir version && cd .. &&
      alembic revision --autogenerate -m 'first migrate into docker' &&
      alembic upgrade head &&
      uvicorn run:app --host 0.0.0.0 --reload
      "
    networks:
      - menu_app_network
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgresql_db
    restart: always
    image: postgres:15.1-alpine
    env_file:
      - .env.docker
    expose:
      - 5433
    ports:
      - "5433:5432"
    networks:
      - menu_app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  menu_app_network:
