version: '3.8'

services:
  test_app:
    container_name: test_app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    entrypoint:
      sh -c "
      alembic revision --autogenerate -m 'first migrate into docker' &&
      alembic upgrade head &&
      pytest -vv
      "
    networks:
      - test_app_network
    depends_on:
      test_postgres:
        condition: service_healthy

  test_postgres:
    container_name: test_db
    restart: always
    image: postgres:15.1-alpine
    env_file:
      - .env.docker
    expose:
      - 5432
    ports:
      - "54321:5432"
    networks:
      - test_app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test_app_network:
