version: '3.8'

services:
  test_app:
    container_name: test_app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - test_menu_app
    environment:
      HOST: test_postgres
      USER: postgres
      PASSWORD: password
      TEST_DB_NAME: test_db
    entrypoint:
      sh -c "
      pytest -vv
      "
    depends_on:
      postgresql_test:
        condition: service_healthy

  postgresql_test:
    container_name: test_postgres
    restart: always
    image: postgres:15.1-alpine
    networks:
      - test_menu_app
    environment:
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: password
      PGUSER: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    expose:
      - 5434
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test_menu_app:
    driver: bridge
