version: '3.8'

services:
  test_app:
    container_name: test_app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - test_menu_app
    env_file:
      - .env.tests
    entrypoint:
      sh -c "
      cd alembic && mkdir version && cd .. &&
      alembic revision --autogenerate -m 'first migrate into docker for testing' &&
      alembic upgrade head &&
      pytest -vv
      "
    depends_on:
      postgresql_test:
        condition: service_healthy

  postgresql_test:
    container_name: test_postgres
    restart: always
    image: postgres:15.1-alpine
    networks:
      - test_menu_app
    env_file:
      - .env.tests
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test_menu_app: